# Generated by Django 5.0.3 on 2024-03-27 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 4, 2, 1, 346523, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2024, 3, 27, 4, 2, 10, 863975, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default=datetime.datetime(2024, 3, 27, 4, 7, 43, 262932, tzinfo=datetime.timezone.utc), upload_to='profile_pictures/'),
            preserve_default=False,
        ),
    ]
